#!/usr/bin/env python
#
# Copyright 2012 Free Software Foundation, Inc.
#
# This file is part of GNU Radio
#
# GNU Radio is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# GNU Radio is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Radio; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street,
# Boston, MA 02110-1301, USA.
#

from analysis import metafileread
from optparse import OptionParser


if __name__ == "__main__":
    usage="%prog: [options] filename"
    description = "Read in a GNU Radio file with meta data, extracts the header and prints it."

    parser = OptionParser(conflict_handler="resolve",
                          usage=usage, description=description)
    parser.add_option("-D", "--detached", action="store_true", default=False,
                      help="Used if header is detached.")
    (options, args) = parser.parse_args ()

    if(len(args) < 1):
        sys.stderr.write("No filename given\n")
        sys.exit(1)

    filename = args[0]
    metafileread.rfm(filename, options.detached)
